name: BeigeNoob
main: com.thevoxelbox.voxelguest.VoxelGuest
author: VoxelPlugineering and 128keaton
version: 4.0.1a
website: http://voxelwiki.com/minecraft/VoxelGuest and http://www.keatonburleson.com

commands:
  afk:
    aliases: [away]
    usage: /<command>
  opass:
    aliases: [offlinepass, offlinepassword]
    usage: /<command> (password)
  opardon:
    aliases: [offlinepardon]
    usage: /<command> [user]
  who:
    aliases: [online, list, plrz]
    usage: /<command>
  ban:
    aliases: [banp, esc, banh]
    usage: /<command> [user] [reason]
  unban:
    aliases: [unbanp]
    usage: /<command> [user]
  gag:
    aliases: [gagp]
    usage: /<command> [user] [reason]
  kick:
    aliases: [kickp]
    usage: /<command> [user] [reason]